const { starterTemplates } = require("../utils/problemTemplates");

const S = starterTemplates();

function tc(input, expectedOutput, isHidden = false) {
  return { input: input.endsWith("\n") ? input : `${input}\n`, expectedOutput: expectedOutput.endsWith("\n") ? expectedOutput : `${expectedOutput}\n`, isHidden };
}

function problem({
  slug,
  title,
  difficulty,
  descriptionMarkdown,
  inputDescription,
  outputDescription,
  constraints = "",
  tags,
  testCases,
}) {
  const visible = testCases.filter((t) => !t.isHidden);
  return {
    slug,
    title,
    difficulty,
    descriptionMarkdown,
    inputDescription,
    outputDescription,
    constraints,
    tags,
    testCases,
    examples: visible.slice(0, 2).map((t) => ({
      input: t.input.trimEnd(),
      output: t.expectedOutput.trimEnd(),
      explanation: "",
    })),
    starterCode: {
      javascript: S.javascript,
      python: S.python,
      java: S.java,
      c: S.c,
      cpp: S.cpp,
    },
    isPublished: true,
    problemType: "practice_problem",
  };
}

/** 60 practice problems with correct test cases (upsert by slug). */
const PRACTICE_BANK = [
  problem({
    slug: "sum-two-numbers",
    title: "Sum Two Numbers",
    difficulty: "easy",
    descriptionMarkdown: "Read two integers and print their sum.",
    inputDescription: "Two integers `a` and `b` on one line.",
    outputDescription: "Print `a + b`.",
    tags: ["math", "basics"],
    testCases: [tc("1 2", "3"), tc("10 20", "30", true), tc("-5 8", "3")],
  }),
  problem({
    slug: "difference-two-numbers",
    title: "Difference Two Numbers",
    difficulty: "easy",
    descriptionMarkdown: "Read two integers and print `a - b`.",
    inputDescription: "Two integers on one line.",
    outputDescription: "Print the difference.",
    tags: ["math", "basics"],
    testCases: [tc("10 3", "7"), tc("3 10", "-7", true)],
  }),
  problem({
    slug: "product-two-numbers",
    title: "Product Two Numbers",
    difficulty: "easy",
    descriptionMarkdown: "Read two integers and print their product.",
    inputDescription: "Two integers on one line.",
    outputDescription: "Print the product.",
    tags: ["math"],
    testCases: [tc("6 7", "42"), tc("-3 4", "-12", true)],
  }),
  problem({
    slug: "maximum-of-two-numbers",
    title: "Maximum of Two Numbers",
    difficulty: "easy",
    descriptionMarkdown: "Print the larger of two integers.",
    inputDescription: "Two integers on one line.",
    outputDescription: "Print the maximum.",
    tags: ["math"],
    testCases: [tc("10 25", "25"), tc("25 10", "25", true)],
  }),
  problem({
    slug: "minimum-of-two-numbers",
    title: "Minimum of Two Numbers",
    difficulty: "easy",
    descriptionMarkdown: "Print the smaller of two integers.",
    inputDescription: "Two integers on one line.",
    outputDescription: "Print the minimum.",
    tags: ["math"],
    testCases: [tc("10 25", "10"), tc("-1 -5", "-5", true)],
  }),
  problem({
    slug: "check-even-or-odd",
    title: "Check Even or Odd",
    difficulty: "easy",
    descriptionMarkdown: "Print `Even` if the number is even, otherwise `Odd`.",
    inputDescription: "One integer `n`.",
    outputDescription: "`Even` or `Odd`.",
    tags: ["basics"],
    testCases: [tc("4", "Even"), tc("7", "Odd"), tc("0", "Even", true)],
  }),
  problem({
    slug: "absolute-value",
    title: "Absolute Value",
    difficulty: "easy",
    descriptionMarkdown: "Print the absolute value of `n`.",
    inputDescription: "One integer.",
    outputDescription: "Print `|n|`.",
    tags: ["math"],
    testCases: [tc("-15", "15"), tc("9", "9", true)],
  }),
  problem({
    slug: "square-of-a-number",
    title: "Square of a Number",
    difficulty: "easy",
    descriptionMarkdown: "Print `n * n`.",
    inputDescription: "One integer `n`.",
    outputDescription: "Print the square.",
    tags: ["math"],
    testCases: [tc("12", "144"), tc("-5", "25", true)],
  }),
  problem({
    slug: "sum-of-natural-numbers",
    title: "Sum of Natural Numbers",
    difficulty: "easy",
    descriptionMarkdown: "Print sum `1 + 2 + ... + n`.",
    inputDescription: "One integer `n` (n ≥ 1).",
    outputDescription: "Print the sum.",
    tags: ["math", "loops"],
    testCases: [tc("5", "15"), tc("10", "55", true)],
  }),
  problem({
    slug: "factorial-of-a-number",
    title: "Factorial of a Number",
    difficulty: "easy",
    descriptionMarkdown: "Print `n!` for `0 ≤ n ≤ 12`.",
    inputDescription: "One integer `n`.",
    outputDescription: "Print factorial.",
    tags: ["math", "loops"],
    testCases: [tc("0", "1"), tc("5", "120"), tc("10", "3628800", true)],
  }),
  problem({
    slug: "reverse-a-number",
    title: "Reverse a Number",
    difficulty: "easy",
    descriptionMarkdown: "Reverse the digits of `n` and print the result.",
    inputDescription: "One integer `n`.",
    outputDescription: "Reversed number.",
    tags: ["math"],
    testCases: [tc("123", "321"), tc("1000", "1", true)],
  }),
  problem({
    slug: "count-digits-in-number",
    title: "Count Digits in a Number",
    difficulty: "easy",
    descriptionMarkdown: "Count digits in `n` (ignore sign).",
    inputDescription: "One integer.",
    outputDescription: "Digit count.",
    tags: ["math"],
    testCases: [tc("12345", "5"), tc("0", "1", true)],
  }),
  problem({
    slug: "sum-of-digits",
    title: "Sum of Digits",
    difficulty: "easy",
    descriptionMarkdown: "Print sum of digits of `n`.",
    inputDescription: "One integer.",
    outputDescription: "Digit sum.",
    tags: ["math"],
    testCases: [tc("123", "6"), tc("999", "27", true)],
  }),
  problem({
    slug: "largest-of-three-numbers",
    title: "Largest of Three Numbers",
    difficulty: "easy",
    descriptionMarkdown: "Print the largest of three integers.",
    inputDescription: "Three integers on one line.",
    outputDescription: "Maximum value.",
    tags: ["basics"],
    testCases: [tc("1 9 3", "9"), tc("-1 -2 -3", "-1", true)],
  }),
  problem({
    slug: "smallest-of-three-numbers",
    title: "Smallest of Three Numbers",
    difficulty: "easy",
    descriptionMarkdown: "Print the smallest of three integers.",
    inputDescription: "Three integers on one line.",
    outputDescription: "Minimum value.",
    tags: ["basics"],
    testCases: [tc("1 9 3", "1"), tc("5 5 1", "1", true)],
  }),
  problem({
    slug: "check-leap-year",
    title: "Check Leap Year",
    difficulty: "easy",
    descriptionMarkdown: "Print `Yes` if year is leap, else `No`.",
    inputDescription: "One integer year.",
    outputDescription: "`Yes` or `No`.",
    tags: ["math"],
    testCases: [tc("2024", "Yes"), tc("1900", "No"), tc("2000", "Yes", true)],
  }),
  problem({
    slug: "gcd-of-two-numbers",
    title: "GCD of Two Numbers",
    difficulty: "easy",
    descriptionMarkdown: "Print greatest common divisor of `a` and `b`.",
    inputDescription: "Two positive integers.",
    outputDescription: "GCD.",
    tags: ["math"],
    testCases: [tc("12 18", "6"), tc("7 13", "1", true)],
  }),
  problem({
    slug: "lcm-of-two-numbers",
    title: "LCM of Two Numbers",
    difficulty: "easy",
    descriptionMarkdown: "Print least common multiple of `a` and `b`.",
    inputDescription: "Two positive integers.",
    outputDescription: "LCM.",
    tags: ["math"],
    testCases: [tc("12 18", "36"), tc("4 6", "12", true)],
  }),
  problem({
    slug: "check-prime-number",
    title: "Check Prime Number",
    difficulty: "easy",
    descriptionMarkdown: "Print `Yes` if prime, else `No`.",
    inputDescription: "One integer `n` (n ≥ 2).",
    outputDescription: "`Yes` or `No`.",
    tags: ["math"],
    testCases: [tc("7", "Yes"), tc("9", "No"), tc("2", "Yes", true)],
  }),
  problem({
    slug: "nth-fibonacci-number",
    title: "Nth Fibonacci Number",
    difficulty: "easy",
    descriptionMarkdown: "Print F(n) where F(0)=0, F(1)=1.",
    inputDescription: "One integer `n` (0 ≤ n ≤ 30).",
    outputDescription: "Fibonacci value.",
    tags: ["math", "dp"],
    testCases: [tc("0", "0"), tc("7", "13"), tc("10", "55", true)],
  }),
  problem({
    slug: "palindrome-number-check",
    title: "Palindrome Number Check",
    difficulty: "easy",
    descriptionMarkdown: "Print `Yes` if number reads same forwards/backwards.",
    inputDescription: "One integer.",
    outputDescription: "`Yes` or `No`.",
    tags: ["math"],
    testCases: [tc("121", "Yes"), tc("123", "No"), tc("1221", "Yes", true)],
  }),
  problem({
    slug: "count-vowels-in-string",
    title: "Count Vowels in String",
    difficulty: "easy",
    descriptionMarkdown: "Count vowels (a,e,i,o,u) in a lowercase string.",
    inputDescription: "One lowercase word.",
    outputDescription: "Vowel count.",
    tags: ["strings"],
    testCases: [tc("hello", "2"), tc("sky", "0", true)],
  }),
  problem({
    slug: "reverse-a-string",
    title: "Reverse a String",
    difficulty: "easy",
    descriptionMarkdown: "Print the reverse of the given string.",
    inputDescription: "One word (no spaces).",
    outputDescription: "Reversed string.",
    tags: ["strings"],
    testCases: [tc("code", "edoc"), tc("a", "a", true)],
  }),
  problem({
    slug: "sum-of-array-elements",
    title: "Sum of Array Elements",
    difficulty: "easy",
    descriptionMarkdown: "First line: `n`. Second line: `n` integers. Print their sum.",
    inputDescription: "Count then space-separated array.",
    outputDescription: "Sum.",
    tags: ["arrays"],
    testCases: [tc("3\n1 2 3", "6"), tc("5\n1 1 1 1 1", "5", true)],
  }),
  problem({
    slug: "maximum-in-array",
    title: "Maximum in Array",
    difficulty: "easy",
    descriptionMarkdown: "Print the maximum element in the array.",
    inputDescription: "Count then array elements.",
    outputDescription: "Maximum value.",
    tags: ["arrays"],
    testCases: [tc("4\n3 9 1 7", "9"), tc("1\n-5", "-5", true)],
  }),
  problem({
    slug: "minimum-in-array",
    title: "Minimum in Array",
    difficulty: "easy",
    descriptionMarkdown: "Print the minimum element in the array.",
    inputDescription: "Count then array elements.",
    outputDescription: "Minimum value.",
    tags: ["arrays"],
    testCases: [tc("4\n3 9 1 7", "1"), tc("2\n-1 -2", "-2", true)],
  }),
  problem({
    slug: "count-even-numbers-in-array",
    title: "Count Even Numbers in Array",
    difficulty: "easy",
    descriptionMarkdown: "Count how many elements are even.",
    inputDescription: "Count then array.",
    outputDescription: "Even count.",
    tags: ["arrays"],
    testCases: [tc("5\n1 2 3 4 5", "2"), tc("3\n2 4 6", "3", true)],
  }),
  problem({
    slug: "linear-search-index",
    title: "Linear Search Index",
    difficulty: "easy",
    descriptionMarkdown: "Line1: n. Line2: array. Line3: target. Print index (0-based) or `-1`.",
    inputDescription: "Array size, elements, target.",
    outputDescription: "Index or -1.",
    tags: ["arrays", "search"],
    testCases: [tc("5\n1 3 5 7 9\n5", "2"), tc("3\n1 2 3\n4", "-1", true)],
  }),
  problem({
    slug: "celsius-to-fahrenheit",
    title: "Celsius to Fahrenheit",
    difficulty: "easy",
    descriptionMarkdown: "Convert C to F using `F = C * 9/5 + 32`. Print integer (rounded).",
    inputDescription: "One integer Celsius.",
    outputDescription: "Fahrenheit (rounded).",
    tags: ["math"],
    testCases: [tc("0", "32"), tc("100", "212", true)],
  }),
  problem({
    slug: "simple-interest",
    title: "Simple Interest",
    difficulty: "easy",
    descriptionMarkdown: "SI = P*R*T/100. Print integer SI.",
    inputDescription: "Principal, rate, time on one line.",
    outputDescription: "Simple interest.",
    tags: ["math"],
    testCases: [tc("1000 5 2", "100"), tc("500 10 1", "50", true)],
  }),
  problem({
    slug: "second-largest-in-array",
    title: "Second Largest in Array",
    difficulty: "medium",
    descriptionMarkdown: "Print second largest distinct value (array has ≥2 elements).",
    inputDescription: "Count then distinct-friendly array.",
    outputDescription: "Second largest.",
    tags: ["arrays"],
    testCases: [tc("5\n10 20 30 40 50", "40"), tc("4\n7 7 5 9", "7", true)],
  }),
  problem({
    slug: "remove-duplicates-sorted-length",
    title: "Unique Count in Sorted Array",
    difficulty: "medium",
    descriptionMarkdown: "Array is sorted ascending. Print number of unique elements.",
    inputDescription: "Count then sorted array.",
    outputDescription: "Unique count.",
    tags: ["arrays", "two-pointers"],
    testCases: [tc("6\n1 1 2 2 3 4", "4"), tc("3\n5 5 5", "1", true)],
  }),
  problem({
    slug: "bubble-sort-array",
    title: "Sort Array Ascending",
    difficulty: "medium",
    descriptionMarkdown: "Sort array in ascending order. Print space-separated values.",
    inputDescription: "Count then array.",
    outputDescription: "Sorted array on one line.",
    tags: ["sorting", "arrays"],
    testCases: [tc("5\n5 1 4 2 3", "1 2 3 4 5"), tc("1\n9", "9", true)],
  }),
  problem({
    slug: "binary-search-position",
    title: "Binary Search Position",
    difficulty: "medium",
    descriptionMarkdown: "Sorted array. Print index of target or `-1`.",
    inputDescription: "n, sorted array, target.",
    outputDescription: "Index or -1.",
    tags: ["search", "arrays"],
    testCases: [tc("5\n1 3 5 7 9\n7", "3"), tc("4\n2 4 6 8\n1", "-1", true)],
  }),
  problem({
    slug: "kadanes-maximum-subarray-sum",
    title: "Maximum Subarray Sum",
    difficulty: "medium",
    descriptionMarkdown: "Print maximum sum of any contiguous subarray (Kadane).",
    inputDescription: "Count then array (may include negatives).",
    outputDescription: "Maximum subarray sum.",
    tags: ["dp", "arrays"],
    testCases: [tc("9\n-2 1 -3 4 -1 2 1 -5 4", "6"), tc("3\n-1 -2 -3", "-1", true)],
  }),
  problem({
    slug: "stock-max-profit",
    title: "Best Time to Buy and Sell Stock",
    difficulty: "medium",
    descriptionMarkdown: "One transaction max. Print maximum profit.",
    inputDescription: "Count then daily prices.",
    outputDescription: "Max profit.",
    tags: ["arrays", "greedy"],
    testCases: [tc("6\n7 1 5 3 6 4", "5"), tc("2\n7 6", "0", true)],
  }),
  problem({
    slug: "leaders-in-array",
    title: "Leaders in Array",
    difficulty: "medium",
    descriptionMarkdown: "Print leaders (greater than all elements to the right), space-separated in order.",
    inputDescription: "Count then array.",
    outputDescription: "Leaders separated by spaces.",
    tags: ["arrays"],
    testCases: [tc("6\n16 17 4 3 5 2", "17 5 2"), tc("3\n10 9 8", "10 9 8", true)],
  }),
  problem({
    slug: "merge-two-sorted-arrays",
    title: "Merge Two Sorted Arrays",
    difficulty: "medium",
    descriptionMarkdown: "Line1: n m. Line2: sorted A. Line3: sorted B. Print merged sorted array.",
    inputDescription: "Sizes and two sorted arrays.",
    outputDescription: "Merged sorted output.",
    tags: ["arrays", "two-pointers"],
    testCases: [tc("3 3\n1 3 5\n2 4 6", "1 2 3 4 5 6"), tc("1 1\n1\n2", "1 2", true)],
  }),
  problem({
    slug: "find-missing-number-1-to-n",
    title: "Missing Number 1 to N",
    difficulty: "medium",
    descriptionMarkdown: "Array contains n distinct numbers from 1..n+1 except one missing. Print missing.",
    inputDescription: "Count n, then n numbers.",
    outputDescription: "Missing number.",
    tags: ["math", "arrays"],
    testCases: [tc("3\n1 2 4", "3"), tc("4\n1 2 3 5", "4", true)],
  }),
  problem({
    slug: "anagram-check",
    title: "Anagram Check",
    difficulty: "medium",
    descriptionMarkdown: "Two lowercase words. Print `Yes` if anagrams.",
    inputDescription: "Two lines, words without spaces.",
    outputDescription: "`Yes` or `No`.",
    tags: ["strings"],
    testCases: [tc("listen\ntsilent", "Yes"), tc("abc\ndef", "No", true)],
  }),
  problem({
    slug: "valid-parentheses",
    title: "Valid Parentheses",
    difficulty: "medium",
    descriptionMarkdown: "String of `()[]{}` only. Print `Yes` if valid.",
    inputDescription: "One bracket string.",
    outputDescription: "`Yes` or `No`.",
    tags: ["stack", "strings"],
    testCases: [tc("()[]{}", "Yes"), tc("(]", "No"), tc("([)]", "No", true)],
  }),
  problem({
    slug: "integer-square-root",
    title: "Integer Square Root",
    difficulty: "medium",
    descriptionMarkdown: "Print floor(sqrt(n)) for non-negative n.",
    inputDescription: "One non-negative integer.",
    outputDescription: "Floor square root.",
    tags: ["math", "binary-search"],
    testCases: [tc("16", "4"), tc("20", "4", true)],
  }),
  problem({
    slug: "power-of-a-number",
    title: "Power of a Number",
    difficulty: "medium",
    descriptionMarkdown: "Print `a^b` (b ≥ 0, fits in 64-bit).",
    inputDescription: "Base and exponent on one line.",
    outputDescription: "Power result.",
    tags: ["math"],
    testCases: [tc("2 10", "1024"), tc("5 0", "1", true)],
  }),
  problem({
    slug: "count-occurrences-in-array",
    title: "Count Occurrences in Array",
    difficulty: "medium",
    descriptionMarkdown: "Count how many times `x` appears.",
    inputDescription: "n, array, then x.",
    outputDescription: "Count.",
    tags: ["arrays"],
    testCases: [tc("6\n1 2 2 3 2 4\n2", "3"), tc("3\n1 1 1\n2", "0", true)],
  }),
  problem({
    slug: "rotate-array-right-by-one",
    title: "Rotate Array Right by One",
    difficulty: "medium",
    descriptionMarkdown: "Rotate array right by 1. Print result space-separated.",
    inputDescription: "Count then array.",
    outputDescription: "Rotated array.",
    tags: ["arrays"],
    testCases: [tc("5\n1 2 3 4 5", "5 1 2 3 4"), tc("1\n9", "9", true)],
  }),
  problem({
    slug: "count-pairs-with-given-sum",
    title: "Count Pairs With Given Sum",
    difficulty: "medium",
    descriptionMarkdown: "Count unordered pairs (i<j) with sum equal to `k`.",
    inputDescription: "n, array, k.",
    outputDescription: "Pair count.",
    tags: ["arrays"],
    testCases: [tc("5\n1 5 7 1 5\n6", "3"), tc("3\n1 2 3\n10", "0", true)],
  }),
  problem({
    slug: "longest-word-length",
    title: "Longest Word Length",
    difficulty: "medium",
    descriptionMarkdown: "Sentence of lowercase words separated by spaces. Print length of longest word.",
    inputDescription: "One line sentence.",
    outputDescription: "Max word length.",
    tags: ["strings"],
    testCases: [tc("code learn is fun", "5"), tc("a bb ccc", "3", true)],
  }),
  problem({
    slug: "armstrong-number-check",
    title: "Armstrong Number Check",
    difficulty: "medium",
    descriptionMarkdown: "Print `Yes` if number equals sum of digits^digitCount.",
    inputDescription: "One integer.",
    outputDescription: "`Yes` or `No`.",
    tags: ["math"],
    testCases: [tc("153", "Yes"), tc("123", "No", true)],
  }),
  problem({
    slug: "perfect-square-check",
    title: "Perfect Square Check",
    difficulty: "medium",
    descriptionMarkdown: "Print `Yes` if n is a perfect square.",
    inputDescription: "One non-negative integer.",
    outputDescription: "`Yes` or `No`.",
    tags: ["math"],
    testCases: [tc("16", "Yes"), tc("15", "No", true)],
  }),
  problem({
    slug: "trailing-zeros-in-factorial",
    title: "Trailing Zeros in Factorial",
    difficulty: "medium",
    descriptionMarkdown: "Count trailing zeros in `n!`.",
    inputDescription: "One integer n (n ≤ 100000).",
    outputDescription: "Trailing zero count.",
    tags: ["math"],
    testCases: [tc("5", "1"), tc("25", "6", true)],
  }),
  problem({
    slug: "digit-sum-until-single",
    title: "Digital Root",
    difficulty: "medium",
    descriptionMarkdown: "Repeatedly sum digits until one digit remains.",
    inputDescription: "One positive integer.",
    outputDescription: "Single digit result.",
    tags: ["math"],
    testCases: [tc("9875", "2"), tc("9", "9", true)],
  }),
  problem({
    slug: "max-consecutive-ones",
    title: "Max Consecutive Ones",
    difficulty: "medium",
    descriptionMarkdown: "Binary array (0/1). Print longest run of 1s.",
    inputDescription: "Count then 0/1 array.",
    outputDescription: "Max consecutive ones.",
    tags: ["arrays"],
    testCases: [tc("6\n1 1 0 1 1 1", "3"), tc("4\n0 0 0 0", "0", true)],
  }),
  problem({
    slug: "longest-increasing-subsequence-length",
    title: "Longest Increasing Subsequence Length",
    difficulty: "hard",
    descriptionMarkdown: "Print length of longest strictly increasing subsequence.",
    inputDescription: "Count then array (n ≤ 25).",
    outputDescription: "LIS length.",
    tags: ["dp", "arrays"],
    testCases: [tc("6\n10 9 2 5 3 7", "3"), tc("5\n1 2 3 4 5", "5", true)],
  }),
  problem({
    slug: "coin-change-minimum-coins",
    title: "Coin Change Minimum Coins",
    difficulty: "hard",
    descriptionMarkdown: "Line1: amount. Line2: k and k coin values. Print min coins or `-1`.",
    inputDescription: "Amount and coin list.",
    outputDescription: "Minimum coins.",
    tags: ["dp"],
    testCases: [tc("11\n3 1 2 5", "3"), tc("3\n1 2", "-1", true)],
  }),
  problem({
    slug: "longest-common-subsequence-length",
    title: "Longest Common Subsequence Length",
    difficulty: "hard",
    descriptionMarkdown: "Two strings (lowercase). Print LCS length.",
    inputDescription: "Two lines, strings.",
    outputDescription: "LCS length.",
    tags: ["dp", "strings"],
    testCases: [tc("abcde\nace", "3"), tc("abc\ndef", "0", true)],
  }),
  problem({
    slug: "edit-distance",
    title: "Edit Distance",
    difficulty: "hard",
    descriptionMarkdown: "Minimum insert/delete/replace ops to convert word1 to word2.",
    inputDescription: "Two lowercase words.",
    outputDescription: "Edit distance.",
    tags: ["dp", "strings"],
    testCases: [tc("horse\nros", "3"), tc("abc\nabc", "0", true)],
  }),
  problem({
    slug: "jump-game-reachable",
    title: "Jump Game Reachable",
    difficulty: "hard",
    descriptionMarkdown: "Each element is max jump length from that index. Print `Yes` if last index reachable.",
    inputDescription: "Count then jump array.",
    outputDescription: "`Yes` or `No`.",
    tags: ["greedy", "arrays"],
    testCases: [tc("5\n2 3 1 1 4", "Yes"), tc("3\n3 2 1", "No", true)],
  }),
  problem({
    slug: "trapping-rain-water",
    title: "Trapping Rain Water",
    difficulty: "hard",
    descriptionMarkdown: "Elevation map (non-negative heights). Print total trapped water units.",
    inputDescription: "Count then heights.",
    outputDescription: "Water units.",
    tags: ["arrays", "two-pointers"],
    testCases: [tc("6\n0 1 0 2 1 0", "1"), tc("12\n0 1 0 2 1 0 1 3 2 1 2 1", "6", true)],
  }),
  problem({
    slug: "matrix-diagonal-sum",
    title: "Matrix Diagonal Sum",
    difficulty: "easy",
    descriptionMarkdown: "Square matrix n×n. Print sum of primary diagonal.",
    inputDescription: "n then n lines of n integers.",
    outputDescription: "Diagonal sum.",
    tags: ["matrix"],
    testCases: [tc("3\n1 2 3\n4 5 6\n7 8 9", "15"), tc("2\n1 0\n0 1", "2", true)],
  }),
  problem({
    slug: "count-primes-up-to-n",
    title: "Count Primes Up To N",
    difficulty: "medium",
    descriptionMarkdown: "Count primes strictly less than `n` (n ≤ 1000000).",
    inputDescription: "One integer n.",
    outputDescription: "Prime count.",
    tags: ["math"],
    testCases: [tc("10", "4"), tc("2", "0", true)],
  }),
  problem({
    slug: "majority-element",
    title: "Majority Element",
    difficulty: "medium",
    descriptionMarkdown: "Array has a majority element (> n/2). Print it.",
    inputDescription: "Count then array.",
    outputDescription: "Majority value.",
    tags: ["arrays"],
    testCases: [tc("3\n3 3 2", "3"), tc("7\n2 2 2 2 3 3 3", "2", true)],
  }),
  problem({
    slug: "product-array-sign",
    title: "Sign of Product of Array",
    difficulty: "easy",
    descriptionMarkdown: "Print `positive`, `negative`, or `zero` for product sign (no overflow).",
    inputDescription: "Count then non-zero ints (may include zero).",
    outputDescription: "Sign label.",
    tags: ["arrays"],
    testCases: [tc("3\n-1 -2 -3", "negative"), tc("2\n0 5", "zero", true)],
  }),
  problem({
    slug: "find-duplicate-number",
    title: "Find Duplicate Number",
    difficulty: "medium",
    descriptionMarkdown: "Array of n+1 integers in range 1..n with one duplicate. Print duplicate.",
    inputDescription: "Count n, then n+1 numbers.",
    outputDescription: "Duplicate value.",
    tags: ["arrays"],
    testCases: [tc("3\n1 3 4 2 2", "2"), tc("1\n1 1", "1", true)],
  }),
  problem({
    slug: "longest-palindrome-substring-length",
    title: "Longest Palindrome Substring Length",
    difficulty: "hard",
    descriptionMarkdown: "Print length of longest palindromic substring.",
    inputDescription: "One lowercase string (length ≤ 100).",
    outputDescription: "Maximum palindrome length.",
    tags: ["strings", "dp"],
    testCases: [tc("babad", "3"), tc("cbbd", "2", true)],
  }),
  problem({
    slug: "subarray-with-zero-sum",
    title: "Subarray With Zero Sum Exists",
    difficulty: "medium",
    descriptionMarkdown: "Print `Yes` if any contiguous subarray sums to 0.",
    inputDescription: "Count then array.",
    outputDescription: "`Yes` or `No`.",
    tags: ["arrays", "hash"],
    testCases: [tc("5\n4 2 -3 1 6", "Yes"), tc("3\n1 2 3", "No", true)],
  }),
  problem({
    slug: "maximum-product-subarray",
    title: "Maximum Product Subarray",
    difficulty: "hard",
    descriptionMarkdown: "Print maximum product of any contiguous subarray.",
    inputDescription: "Count then array.",
    outputDescription: "Maximum product.",
    tags: ["dp", "arrays"],
    testCases: [tc("4\n2 3 -2 4", "6"), tc("3\n-2 0 -1", "0", true)],
  }),
  problem({
    slug: "rotate-matrix-90-degrees-sum",
    title: "Sum After Matrix Transpose",
    difficulty: "medium",
    descriptionMarkdown: "Square matrix. Transpose then print sum of all elements.",
    inputDescription: "n and n×n matrix.",
    outputDescription: "Sum after transpose.",
    tags: ["matrix"],
    testCases: [tc("2\n1 2\n3 4", "10"), tc("1\n5", "5", true)],
  }),
  problem({
    slug: "intersection-of-two-arrays-count",
    title: "Intersection Count of Two Arrays",
    difficulty: "easy",
    descriptionMarkdown: "Count distinct values present in both arrays.",
    inputDescription: "n, array A, m, array B.",
    outputDescription: "Intersection size.",
    tags: ["arrays", "hash"],
    testCases: [tc("3\n1 2 2\n4\n3 2 2 4", "2"), tc("2\n1 2\n2\n3 4", "0", true)],
  }),
  problem({
    slug: "check-sorted-array",
    title: "Check Sorted Array",
    difficulty: "easy",
    descriptionMarkdown: "Print `Yes` if array is non-decreasing.",
    inputDescription: "Count then array.",
    outputDescription: "`Yes` or `No`.",
    tags: ["arrays"],
    testCases: [tc("4\n1 2 2 5", "Yes"), tc("3\n3 2 1", "No", true)],
  }),
  problem({
    slug: "first-non-repeating-character-index",
    title: "First Non-Repeating Character Index",
    difficulty: "medium",
    descriptionMarkdown: "Lowercase string. Print 0-based index of first non-repeating char, or `-1`.",
    inputDescription: "One string.",
    outputDescription: "Index or -1.",
    tags: ["strings", "hash"],
    testCases: [tc("leetcode", "0"), tc("aabb", "-1", true)],
  }),
];

module.exports = { PRACTICE_BANK };
